Repository TheBevyFlock/bevy_new_2d, pull requests merged in 2025-05, with the labels that each got.

#365 Add `bevy_lint` support
  .github/workflows/ci.yaml
  Cargo.toml
  Cargo.toml.template
  docs/tooling.md
  docs/workflows.md
  src/demo/animation.rs
  src/demo/movement.rs
  src/demo/player.rs
  src/lib.rs
  src/lib.rs.template
  src/main.rs
  src/main.rs.template
  src/screens/splash.rs
Labels: enhancement

#410 Update CI/CD
  .cargo/config_ci.toml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/release.yaml.template
Labels: S-Blocked

#412 Fix newlines in generated release.yaml
  .github/workflows/release.yaml.template
Labels: D-Trivial, C-Code-Quality, A-Generate

#386 Install bevy_cli with cargo-binstall
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/release.yaml.template
Labels: A-Build-System
